/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AschildRouteImport } from './routes/aschild'
import { Route as CompoundComponentsRouteImport } from './routes/compound-components'
import { Route as HeadlessHookPropGettersRouteImport } from './routes/headless-hook-prop-getters'
import { Route as PolymorphicAsPropRouteImport } from './routes/polymorphic-as-prop'
import { Route as SomewhereRouteImport } from './routes/somewhere'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AschildRoute = AschildRouteImport.update({
  id: '/aschild',
  path: '/aschild',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundComponentsRoute = CompoundComponentsRouteImport.update({
  id: '/compound-components',
  path: '/compound-components',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadlessHookPropGettersRoute = HeadlessHookPropGettersRouteImport.update({
  id: '/headless-hook-prop-getters',
  path: '/headless-hook-prop-getters',
  getParentRoute: () => rootRouteImport,
} as any)
const PolymorphicAsPropRoute = PolymorphicAsPropRouteImport.update({
  id: '/polymorphic-as-prop',
  path: '/polymorphic-as-prop',
  getParentRoute: () => rootRouteImport,
} as any)
const SomewhereRoute = SomewhereRouteImport.update({
  id: '/somewhere',
  path: '/somewhere',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aschild': typeof AschildRoute
  '/compound-components': typeof CompoundComponentsRoute
  '/headless-hook-prop-getters': typeof HeadlessHookPropGettersRoute
  '/polymorphic-as-prop': typeof PolymorphicAsPropRoute
  '/somewhere': typeof SomewhereRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aschild': typeof AschildRoute
  '/compound-components': typeof CompoundComponentsRoute
  '/headless-hook-prop-getters': typeof HeadlessHookPropGettersRoute
  '/polymorphic-as-prop': typeof PolymorphicAsPropRoute
  '/somewhere': typeof SomewhereRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aschild': typeof AschildRoute
  '/compound-components': typeof CompoundComponentsRoute
  '/headless-hook-prop-getters': typeof HeadlessHookPropGettersRoute
  '/polymorphic-as-prop': typeof PolymorphicAsPropRoute
  '/somewhere': typeof SomewhereRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aschild'
    | '/compound-components'
    | '/headless-hook-prop-getters'
    | '/polymorphic-as-prop'
    | '/somewhere'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aschild'
    | '/compound-components'
    | '/headless-hook-prop-getters'
    | '/polymorphic-as-prop'
    | '/somewhere'
  id:
    | '__root__'
    | '/'
    | '/aschild'
    | '/compound-components'
    | '/headless-hook-prop-getters'
    | '/polymorphic-as-prop'
    | '/somewhere'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AschildRoute: typeof AschildRoute
  CompoundComponentsRoute: typeof CompoundComponentsRoute
  HeadlessHookPropGettersRoute: typeof HeadlessHookPropGettersRoute
  PolymorphicAsPropRoute: typeof PolymorphicAsPropRoute
  SomewhereRoute: typeof SomewhereRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aschild': {
      id: '/aschild'
      path: '/aschild'
      fullPath: '/aschild'
      preLoaderRoute: typeof AschildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound-components': {
      id: '/compound-components'
      path: '/compound-components'
      fullPath: '/compound-components'
      preLoaderRoute: typeof CompoundComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headless-hook-prop-getters': {
      id: '/headless-hook-prop-getters'
      path: '/headless-hook-prop-getters'
      fullPath: '/headless-hook-prop-getters'
      preLoaderRoute: typeof HeadlessHookPropGettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polymorphic-as-prop': {
      id: '/polymorphic-as-prop'
      path: '/polymorphic-as-prop'
      fullPath: '/polymorphic-as-prop'
      preLoaderRoute: typeof PolymorphicAsPropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/somewhere': {
      id: '/somewhere'
      path: '/somewhere'
      fullPath: '/somewhere'
      preLoaderRoute: typeof SomewhereRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AschildRoute: AschildRoute,
  CompoundComponentsRoute: CompoundComponentsRoute,
  HeadlessHookPropGettersRoute: HeadlessHookPropGettersRoute,
  PolymorphicAsPropRoute: PolymorphicAsPropRoute,
  SomewhereRoute: SomewhereRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
